export const dishInfo = [
  {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 13,
    healthScore: 7,
    creditsText: "foodista.com",
    sourceName: "foodista.com",
    pricePerServing: 47.4,
    extendedIngredients: [
      {
        id: 18372,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "baking soda",
        nameClean: "baking soda",
        original: "2 teaspoons baking soda",
        originalName: "baking soda",
        amount: 2,
        unit: "teaspoons",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 19334,
        aisle: "Baking",
        image: "light-brown-sugar.jpg",
        consistency: "SOLID",
        name: "firmly brown sugar",
        nameClean: "golden brown sugar",
        original: "1 1/2 cups firmly packed light brown sugar",
        originalName: "firmly packed light brown sugar",
        amount: 1.5,
        unit: "cups",
        meta: ["light", "packed"],
        measures: {
          us: {
            amount: 1.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 354.882,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11424,
        aisle: "Baking",
        image: "pumpkin-puree.jpg",
        consistency: "SOLID",
        name: "pumpkin",
        nameClean: "canned pumpkin",
        original: "16 ounces can pumpkin (Libby's)",
        originalName: "pumpkin (Libby's)",
        amount: 16,
        unit: "ounces",
        meta: ["canned", "(Libby's)"],
        measures: {
          us: {
            amount: 16,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 453.592,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "2 teaspoons cinnamon",
        originalName: "cinnamon",
        amount: 2,
        unit: "teaspoons",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1123,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg.png",
        consistency: "SOLID",
        name: "eggs",
        nameClean: "egg",
        original: "2 eggs, well beaten",
        originalName: "eggs, well beaten",
        amount: 2,
        unit: "",
        meta: ["well beaten"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "wheat flour",
        original: "2 cups flour",
        originalName: "flour",
        amount: 2,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2011,
        aisle: "Spices and Seasonings",
        image: "cloves.jpg",
        consistency: "SOLID",
        name: "ground cloves",
        nameClean: "ground clove",
        original: "1 teaspoon ground cloves",
        originalName: "ground cloves",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 19304,
        aisle: "Baking",
        image: "molasses.jpg",
        consistency: "SOLID",
        name: "molasses",
        nameClean: "molasses",
        original: "1/2 cup molasses",
        originalName: "molasses",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1 teaspoon nutmeg",
        originalName: "nutmeg",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 20033,
        aisle: "Cereal;Baking",
        image: "bran.jpg",
        consistency: "SOLID",
        name: "oat bran",
        nameClean: "oat bran",
        original: "cup oat bran",
        originalName: "oat bran",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "oil",
        nameClean: "butter",
        original: "1 cup oil or butter",
        originalName: "oil or butter",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 12142,
        aisle: "Nuts;Baking",
        image: "pecans.jpg",
        consistency: "SOLID",
        name: "pecans",
        nameClean: "pecans",
        original: "1/4 cup pecans, finely chopped",
        originalName: "pecans, finely chopped",
        amount: 0.25,
        unit: "cup",
        meta: ["finely chopped"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "1/2 teaspoon salt",
        originalName: "salt",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10020077,
        aisle: "Cereal;Health Foods;Baking",
        image: "bran.jpg",
        consistency: "SOLID",
        name: "wheat bran",
        nameClean: "wheat bran",
        original: "cup wheat bran",
        originalName: "wheat bran",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 20078,
        aisle: "Cereal;Health Foods;Baking",
        image: "wheat-germ.png",
        consistency: "SOLID",
        name: "wheat germ",
        nameClean: "wheat germ",
        original: "cup wheat germ",
        originalName: "wheat germ",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 20080,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "whole wheat flour",
        original: "1/2 cup whole wheat flour",
        originalName: "whole wheat flour",
        amount: 0.5,
        unit: "cup",
        meta: ["whole wheat"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 665257,
    title: "Whole Grain Pumpkin Bread",
    readyInMinutes: 45,
    servings: 24,
    sourceUrl:
      "http://www.foodista.com/recipe/NV6J583C/whole-grain-pumpkin-bread",
    image: "https://spoonacular.com/recipeImages/665257-556x370.jpg",
    imageType: "jpg",
    summary:
      'Whole Grain Pumpkin Bread might be just the breakfast you are searching for. One portion of this dish contains about <b>5g of protein</b>, <b>10g of fat</b>, and a total of <b>241 calories</b>. For <b>47 cents per serving</b>, this recipe <b>covers 13%</b> of your daily requirements of vitamins and minerals. This recipe serves 24. It is brought to you by Foodista. A couple people made this recipe, and 13 would say it hit the spot. Head to the store and pick up oil, oat bran, pumpkin, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a good option if you\'re following a <b>lacto ovo vegetarian</b> diet. With a spoonacular <b>score of 66%</b>, this dish is good. Similar recipes are <a href="https://spoonacular.com/recipes/multi-grain-pumpkin-cranberry-bread-66662">Multi-Grain Pumpkin Cranberry Bread</a>, <a href="https://spoonacular.com/recipes/whole-grain-pumpkin-pancakes-1051491">Whole Grain Pumpkin Pancakes</a>, and <a href="https://spoonacular.com/recipes/whole-grain-pumpkin-scones-311551">Whole-Grain Pumpkin Scones</a>.',
    cuisines: [],
    dishTypes: ["dessert", "morning meal", "brunch", "breakfast"],
    diets: ["lacto ovo vegetarian"],
    occasions: [],
    instructions:
      "<ol><li>Preheat oven to 375 degrees. Grease 2 loaf pans. Beat oil, brown sugar and molasses until well blended. Blend in egg and pumpkin. Stir flours, brans, wheat germ, soda, cinnamon, cloves, nutmeg and salt into mixture just until moistened. Fold in nuts. Fill pans and bake about 1 hour, until pick comes out clean. Cool on rack. Better if served the day after cooking.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 375 degrees. Grease 2 loaf pans. Beat oil, brown sugar and molasses until well blended. Blend in egg and pumpkin. Stir flours, brans, wheat germ, soda, cinnamon, cloves, nutmeg and salt into mixture just until moistened. Fold in nuts. Fill pans and bake about 1 hour, until pick comes out clean. Cool on rack. Better if served the day after cooking.",
            ingredients: [
              {
                id: 19334,
                name: "brown sugar",
                localizedName: "brown sugar",
                image: "dark-brown-sugar.png",
              },
              {
                id: 20078,
                name: "wheat germ",
                localizedName: "wheat germ",
                image: "wheat-germ.png",
              },
              {
                id: 2010,
                name: "cinnamon",
                localizedName: "cinnamon",
                image: "cinnamon.jpg",
              },
              {
                id: 19304,
                name: "molasses",
                localizedName: "molasses",
                image: "molasses.jpg",
              },
              {
                id: 11422,
                name: "pumpkin",
                localizedName: "pumpkin",
                image: "pumpkin.png",
              },
              {
                id: 1002011,
                name: "clove",
                localizedName: "clove",
                image: "cloves.jpg",
              },
              {
                id: 2025,
                name: "nutmeg",
                localizedName: "nutmeg",
                image: "ground-nutmeg.jpg",
              },
              {
                id: 12135,
                name: "nuts",
                localizedName: "nuts",
                image: "nuts-mixed.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
              {
                id: 0,
                name: "pop",
                localizedName: "soft drink",
                image: "",
              },
              {
                id: 1123,
                name: "egg",
                localizedName: "egg",
                image: "egg.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404715,
                name: "loaf pan",
                localizedName: "loaf pan",
                image: "loaf-pan.png",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 60,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/whole-grain-pumpkin-bread-665257",
  },
];
